### ISSUE TITLE
how to add new locale?

### ISSUE THREAD

**Issue by linhdoan24** [shubhadip/vuejs3-datepicker#25]
how can i add new locale if not exits

**Comment by shubhadip** [comment]
create a function within `src/components/datepicker/locale/index.ts`  && export it

**Comment by ahoiroman** [comment]
Could you add an example to do this in the docs? This would help a lot of people, I'd suggest :-)

**Comment by shubhadip** [comment]
updated readme with the steps to add new Locale, i hope this will be helpful.

**Comment by ahoiroman** [comment]
Hi. Thank you. As stated here (https://github.com/shubhadip/vuejs3-datepicker/pull/32), I think most people (including me) do not know how to actually _use_ the new locale :-)

**Comment by Tofandel** [comment]
Also adding all the locales like this will prevent locales from being treeshaked, so all locales will always be loaded on one's page
