### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by ahoiroman** [shubhadip/vuejs3-datepicker#27]
Hello everybody,

is this project still maintained? Unfortunately, the component breaks a full page (as described in https://github.com/shubhadip/vuejs3-datepicker/pull/20 ).

I see there have been some merges - maybe it would be possible to release a new version?

If I can help - let me know.

**Comment by shubhadip** [comment]
Hey ahoiroman, 
 library is being Maintained

**Comment by ahoiroman** [comment]
Saw your new release. Thank you very much :-)
