### ISSUE TITLE
"Default" text in slot

### ISSUE THREAD

**Issue by ndovnar** [shubhadip/vuejs3-datepicker#37]
Greetings, thanks for your efforts!
I found a minor issue, it looks like there's forgotten text in the slot.
[here](https://github.com/shubhadip/vuejs3-datepicker/blob/master/src/components/datepicker/DateInput.vue#L68)

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/11501912/168812780-518b616d-daeb-437f-8a25-52c46c0559cd.png">

**Comment by shubhadip** [comment]
the issue is resolved in latest release

**Comment by ndovnar** [comment]
@shubhadip thanks a lot!
