### ISSUE TITLE
Opened event not firing

### ISSUE THREAD

**Issue by darrinsworlds** [shubhadip/vuejs3-datepicker#54]
The opened event is not firing on open of the calendar (however the closed is) using vue3 (3.2.47) and typescript (4.9.5).

Here is the datepicker:
`<datepicker v-model="start" :format="format" calendarClass="calendar-right"
                      @closed="closedCalendarClickHandler" @opened="openedCalendarClickHandler"></datepicker>`

Here is the opened function:
`function openedCalendarClickHandler(): void {
  console.log("in open");
}`

**Comment by shubhadip** [comment]
issue addressed in https://github.com/shubhadip/vuejs3-datepicker/pull/56
