### ISSUE TITLE
Clear button does not work

### ISSUE THREAD

**Issue by rajmondburgaj** [shubhadip/vuejs3-datepicker#55]
I enabled clear button but seems it does not work as expected, first the design is not in place, the icon shows under the box instead of the right side, and secondly it does not nothing.

`<datepicker :value="value" :clear-button="true" @selected="dateSelected"></datepicker>`

`const dateSelected = (date: Date) => {
  alert('date selected')
  value.value = date
}`

![image](https://user-images.githubusercontent.com/7545874/218261301-d362cc90-55a7-45f1-bef7-4bb1e8c5f97f.png)
![image](https://user-images.githubusercontent.com/7545874/218261310-b7bfffc3-3e1a-4381-b156-d91d513fd2e5.png)

**Comment by shubhadip** [comment]
issue addressed in [1.0.1](https://github.com/shubhadip/vuejs3-datepicker/pull/56)
