### ISSUE TITLE
Getting error like "Unknown file extension ".css" " when I am using this package in NUXT 3 with SSR 

### ISSUE THREAD

**Issue by jigarf504** [shubhadip/vuejs3-datepicker#75]
I've installed 'vuejs3-datepicker' in my Nuxt 3 SSR project. After importing the package and implemented it into my component, I encountered a 500 server error (please refer to the attached screenshot).

The previous version of this package worked exceptionally well, meeting all requirements. However, I'm facing issues during the Nuxt 3 upgrade process. I would greatly appreciate it if you could provide a solution.

Thanks in advance!

![image](https://github.com/shubhadip/vuejs3-datepicker/assets/89264159/6d07f141-b955-4061-b8c0-096977a8fdae)

![image](https://github.com/shubhadip/vuejs3-datepicker/assets/89264159/55fd2b49-ee4b-4352-8a4b-d7edd4961bd4)

**Comment by shubhadip** [comment]
sure, let me try to replicate

**Comment by jigarf504** [comment]
Thank you so much. the issue has been resolved. great work.. appreciate.
