### ISSUE TITLE
Wrong Day and Date Match

### ISSUE THREAD

**Issue by manjumjn** [shubhadip/vuejs3-datepicker#76]
Hi, It seems that the date picker is showing wrong Day and Date. Eg. Today Sunday Nov 26 but it shows Nov 26 as Monday. 
![image](https://github.com/shubhadip/vuejs3-datepicker/assets/6279238/bb8bdffe-aeb3-43d1-9d75-85c923a581a5)

**Comment by manjumjn** [comment]
After forking and testing, It seems that if i add `monday-first` it fixes the issue. Should it be enabled by default then?

**Comment by shubhadip** [comment]
issue was with the css have fixed the issue.

**Comment by manjumjn** [comment]
Thanks

**Comment by manjumjn** [comment]
Great. Thanks
