### ISSUE TITLE
Unable to highlight a disabled date

### ISSUE THREAD

**Issue by Ben-Kemp-8433** [shubhadip/vuejs3-datepicker#81]
For our application I created a daterange selector using these datepickers.

The start date should always be before the end date and vice-versa, therefore the respective opposite date has to be disabled. Adding the respective dates into the `disabledDates` object does exactly as it's supposed to, everything after the end date is disabled on the start datepicker and the opposite is true for the end datepicker. All good so far.

Now, with v-model I can give the start date to the start datepicker and pass the end date into the `highlighted="{to: date.end}"`. The same is true for the end datepicker v-model getting date.end and `highlighted="{from: date.start}"`.

What ends up being the issue is that the date.start highlight doesn't show up on the end datepicker, while the start datepicker gets its highlight-end like I'd expect. The highlight-start class doesn't show up on the `from` entry in the `highlighted` object.

I have tried adding `includeDisabled: true` in the `highlighted` object with no luck.

Would anyone be able to help me with this conundrum? If I need to provide some code from my components I can do that too.

**Comment by Ben-Kemp-8433** [comment]
I couldn't find anything in the change logs that would solve my issue, but updating to latest helped.

**Comment by shubhadip** [comment]
can you provide the props that you are passing to the datepicker

**Comment by shubhadip** [comment]
is this correct interpretation of what you are saying :  https://stackblitz.com/edit/vue-bmbjpa?file=src%2FApp.vue

**Comment by Ben-Kemp-8433** [comment]
Thanks for the quick response!

It's close, but I've found how to replicate my issue.

If you replace the `date` in your setup with:
```
    const date = ref({
      start: new Date(),
      end: new Date('2023-12-25'),
    });
```

With these settings, you'll see that today is not .highlight-start in either datepicker, while I'd expect it to be considering it's set to be the `from` of the `highlighted` object.
